version: "3.8"

services:
  db:
    build:
      context: ./postgres
    volumes:
      - ./volumes/db/data:/data
    restart: always
    ports:
      - "5432:5432"
    container_name: ht-db

  backend:
    build:
      context: ../../
    depends_on:
      - db
    network_mode: "host"
    ports:
      - "4000:4000"
    container_name: ht-be
