version: "3.8"
services:
    db:
        image: postgres
        environment:
            POSTGRES_DB: habits-tracker-db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        container_name: ht_db
    server:
        build: .
        depends_on:
            - db
        network_mode: "host"
        ports:
            - "4000:4000"
        container_name: ht_server
